package com.demo.common.model;

import com.demo.common.model.base.BaseMail;
import com.utils.Sendmail;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Mail extends BaseMail<Mail> {
	public static final Mail dao = new Mail();

    public void sendWaitedMail() {
        List<Mail> mails = dao.find("select * FROM mail where sendstatus=0;");
        for (int i = 0; i < (mails.size()>5?5:mails.size()); i++) {
            Mail mail =  mails.get(i);
            try {
                Sendmail.sendMail(mail.getTitle(),mail.getContent() );
                System.out.println("发送："+mail.getTitle());
                mail.setSendstatus(1);
                Thread.sleep(2000);
            } catch (Exception e) {
                e.printStackTrace();
                mail.setSendstatus(2);
            }
            mail.update();
        }
    }
}
